apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: label-injector-webhook
webhooks:
  - name: label-injector.example.com
    clientConfig:
      service:
        name: label-injector-service
        namespace: default
        path: /mutate
      insecureSkipTLSVerify: true
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjakNDQWxxZ0F3SUJBZ0lVZUlXUWprM0pQRC9ybkdtVnQvdXpnYTZ1Qlo4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0xURXJNQ2tHQTFVRUF3d2liR0ZpWld3dGFXNXFaV04wYjNJdGMyVnlkbWxqWlM1a1pXWmhkV3gwTG5OMgpZekFlRncweU5UQXlNVEF5TXpRek5ETmFGdzB5TmpBeU1UQXlNelF6TkROYU1DMHhLekFwQmdOVkJBTU1JbXhoClltVnNMV2x1YW1WamRHOXlMWE5sY25acFkyVXVaR1ZtWVhWc2RDNXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURkN2EzWkFjcm8vTmp0bFNJUzlwbWhsd3ZxWG9LUHZ6QzVtcW5waEhjWgo4WUczVVN4eTUvNU5wVmwwSld0WGpzaEo3WGoxRkRTOHdlanAwRHZuN2ZKMGFDc2MxMVRuSG9ENkVkMUN3ZXZmCnF1VlpiOU1BdWNidjFKdUZTeG1Ba1Npakg2Vzd3YlVaTVVkUW9TWk95YXp3c1RjYXJEVmJ4eXMzRDFGdG0zQy8KTE9QejY4Mk9qYlZmdzRnOCt2cmpFOGZjdkNPZUZtUnZYVlRDL0hXWUVSbGtVMUpSaTc1Y2xuTWxrZ0p5OUFpeAp1NS9jeUEzeHFjNVpYMmF4YlhpYjBrOGZkemNIU291M21yeDR5dkIrV0Rpb3JpNjAxQk16Y2g3bDR4TFU4RkNiCk1KMS8vd3F2c0E2cHZkNnFrZGw1Tyt0Z00vTHR2V1BoeWd5NXlzb3owMENOQWdNQkFBR2pnWWt3Z1lZd1pRWUQKVlIwUkJGNHdYSUlXYkdGaVpXd3RhVzVxWldOMGIzSXRjMlZ5ZG1salpZSWViR0ZpWld3dGFXNXFaV04wYjNJdApjMlZ5ZG1salpTNWtaV1poZFd4MGdpSnNZV0psYkMxcGJtcGxZM1J2Y2kxelpYSjJhV05sTG1SbFptRjFiSFF1CmMzWmpNQjBHQTFVZERnUVdCQlJYQjVLS0U3L1FaaFBnY05McWkwNlFydTZjdGpBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUFiSGtMVzJMRklWVGV1MzZwRERIcmJLa3FXdWlvS0hLUmlqRHFqVGlxaDhMRDRYK1Z2VGVmWjM0MwpGMytYczdyVFRDYnhOSTZNSENPekR2MFVUbUU4SlA1eVdUdGZSK1dwaXhkOGRlYmFqbjA2eWpVYlJybU44MzlKCnE1SjlZSVR1cjdIYTZQMU4vRUdXWm5EcG5YN1hiYzY0Y2E4c3JLUDVqSTh3TTNiWTNwZ0UzT2dkYWF5VVc5cTEKdFM2eTlXMGxvQmI2TnZVQkhYTnZhRms3VEtvQVU2MGx4d2ViWHhOTHArbE9QSlhPUnFXemZqN0VON0Rjak1wZQprUGpxaFgyTGQxdituc014Q1VsZWFEZHBKTU1PR3dJaFJxTGtRMExxekl6TnFDSkhDSjlUckNZSkxWQjRxdUxaCnRpTHRqeWtLZENiNTYwQ3FLUmRSVkowT0s3ZjBCQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    objectSelector:
      matchExpressions:
        - key: rollouts-pod-template-hash
          operator: Exists
    admissionReviewVersions: ["v1"]
    sideEffects: None
