apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
  namespace: default
  annotations:
    github.com/project-slug: MoveRDC/acm-operations
spec:
  replicas: 0
  strategy:
    canary:
      steps:
        - setWeight: 30
        - pause: { duration: 30s }  
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
